apiVersion: v1
kind: Pod
metadata:
  namespace: hxnr
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
        limits:
            cpu: 350m
            memory: 300Mi
        requests:
            cpu: 320m
            memory: 300Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}